### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfb'

### ISSUE THREAD

**Issue by jy95** [blegat/smartcp#1]
Hello,

I was testing your utility with https://github.com/Gp2mv3/Syntheses but I got this message.

Here is the full traceback I got with `make all` : 

```sh
jy95@jy95-VirtualBox:~/Desktop/syntheses$ make all
cd src; smartcp -v -qq -x "make all" -n config.yml
Using config.yml
  Updating EPL-Drive
  Updating EPL-Drive exam
Traceback (most recent call last):
  File "/usr/local/bin/smartcp", line 9, in <module>
    load_entry_point('smartcp==0.1', 'console_scripts', 'smartcp')()
  File "build/bdist.linux-i686/egg/smartcp.py", line 299, in main
  File "build/bdist.linux-i686/egg/smartcp.py", line 195, in smart_copy
  File "build/bdist.linux-i686/egg/smartcp.py", line 104, in build_path
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfb' in position 2: ordinal not in range(128)
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1
```

FYI : 

https://stackoverflow.com/a/9942822 

Closed:

I forgot ubuntu was running your utility with Python 2.7.12 by default and you used an alias for command example.
Sorry for the issue

**Comment by blegat** [comment]
No worry, the issue might be helpful if other have the same issue ;)
You will notice that `make all` is currently quite slow since it does a cartesian product of each argument. Doing `make release` on a specific folder is fast though since it sets each argument with `-s`.
